### ISSUE TITLE
Add section on RFC 8200 compliance

### ISSUE THREAD

**Issue by bemasc** [bemasc/draft-xu-risav#27]
We should add a section discussing RISAV's compliance with RFC 8200.  Specifically, [Section 4](https://www.rfc-editor.org/rfc/rfc8200#section-4) says:

>   Extension headers (except for the Hop-by-Hop Options header) are not
>   processed, inserted, or deleted by any node along a packet's delivery
>   path, until the packet reaches the node (or each of the set of nodes,
>   in the case of multicast) identified in the Destination Address field
>   of the IPv6 header.

This looks like it's not compatible with Transport Mode.  I see a few options:

1. Update RFC 8200 (e.g. to say extension headers can be inserted by one node if they are later deleted)
2. Remove Transport Mode
3. Argue that Transport Mode actually is somehow allowed under RFC 8200.  (Notably, this paragraph is not normative, so it could be taken as merely a description of common practice, rather than a strict requirement.)

**Comment by BasilGuo** [comment]
Yes, we should guarantee RISAV compliance with RFC 8200.

It seems not so easy to update a mature protocol. The modification to IPsec AH is beset with difficulties in ipsecme working group. I think it is also the same at the 6man working group. :joy: 

The insertion action at an extra node may bring other problems we don't see as this violated to RFC 8200 and the communities are opposed to it. So it may be a compromised choice to remove transport mode.

There is also a problem with the Tunnel Mode. The tunnel we set now is established between ASBR and ACS in different ASes. So the problem is whether it is allowed to process the IPsec header at the ASBRs all the time without the consent of ACS. 

For example, we have `AS A` and `AS B` and with `ACS a`, `ACS b`, `ASBR Ra`, and `ASBR Rb` inside separately. Now a packet is sent from `AS A` to `AS B`. It will use the tunnel between `Ra` and `ACS b` while the `Rb` will represent `ACS b` to process the IPsec header in the packet and sends it to the destination host in `AS B`.
```
+---------+                +---------+
|   AS A  |                |  AS  B  |
|        #########   #########       |
| ACS a  #ASBR Ra#---#ASBR Rb# ACS b |
|        #########   #########       |
+---------+                +---------+
```
If so, nothing to disturb. Otherwise, we also should rethink the tunnel mode. :joy:

**Comment by BasilGuo** [comment]
Well, I just rewatched our presentation in IETF 115.

One expert has mentioned that the Transport mode is an optional mode that one should request to use. And if the peer doesn't agree, they still should use Tunnel mode in communication. [YouTube](https://youtu.be/_KL72WYYqm8?t=4396). 

Maybe removing the transport mode is an acceptable solution. Also, link with #7.
